name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install depencencies
      run: |
        sudo apt-get install cppcheck neofetch clang
        neofetch --stdout
    - name: make
      run: make -j4 CXX=clang++
    - name: make test
      run: make -j4 test CXX=clang++
    - name: make install
      run: sudo make install
